создание EmployeeCost
The entity type 'EmployeeCost' requires a primary key to be defined. If you intended to use a keyless entity type call 'HasNoKey() - выдает если в EmployeeCost нет поля Id
Выдает:
InvalidOperationException: No service for type 'Microsoft.AspNetCore.Identity.UserManager`1[_66bitProject.Models.User]' has been registered.